function generateChallenge(challengeType) {
    var challenges = {
        'building': [
            'Go to the Ying Wu College of Computing and take a picture of the entrance.',
            'Find the Albert Dorman Honors College and take a picture.',
            'Take a picture of the NJIT parking deck.',
            'Locate the NJIT Life Sciences and Engineering Center.',
            'Take a picture of the Green building.',
            'Find the NJIT Child Care Center.',
            'Locate the NJIT Warren Street Village.',
            'Take a picture of the Microelectronics Center.',
            'Find the NJIT Campus Center and take a picture.',
            'Take a picture of the GITC building.',
            'Locate the NJIT Wellness and Events Center.',
            'Find the NJIT Eberhardt Hall and take a picture.',
            'Take a picture of the NJIT Faculty Memorial Hall.',
            'Find the NJIT Parking Deck and take a picture.',
            'Locate the NJIT Fenster Hall and take a picture.',
            'Take a picture of the NJIT Central King Building.',
            'Find the NJIT Greek Village and take a picture.',
            'Locate the NJIT Cullimore Hall and take a picture.',
            'Take a picture of the NJIT Weston Hall.',
            'Find the NJIT Biological Sciences Building and take a picture.',
            'Take a picture of the NJIT Tiernan Hall.',
            'Find the NJIT Cypress Hall and take a picture.',
            'Locate the NJIT Summit Street Apartment and take a picture.'
        ],
        'landmark': [
            'Locate the NJIT clock tower.',
            'Find the statue of the NJIT Highlander.',
            'Take a picture with the NJIT sign.',
            'Find the statue of Albert Einstein at NJIT.',
            'Locate the NJIT Babbage Park.',
            'Take a picture at the NJIT Tennis Court.',
            'Find the NJIT Soccer Field.',
            'Locate the NJIT Softball Field.',
            'Take a picture at the NJIT Athletic Field.',
            'Find the NJIT Amphitheater.',
            'Locate the NJIT Veterans Memorial.',
            'Take a picture at the NJIT Fountain.',
            'Find the NJIT Peace Monument.',
            'Locate the NJIT Babbage Park.',
            'Take a picture at the NJIT Alumni Gymnasium.',
            'Find the NJIT Observatory.',
            'Locate the NJIT Solar Carport.',
            'Take a picture at the NJIT Mary Bethune Center.',
            'Find the NJIT Greek Village Lawn.',
            'Locate the NJIT Food Trucks.',
            'Take a picture at the NJIT Spirit Shop.',
            'Find the NJIT Technology and Entrepreneurship Talent Network (TETN).',
            'Locate the NJIT Student Mall.'
        ],
        'sport': [
            'Attend the next NJIT soccer game.',
            'Watch an NJIT basketball practice.',
            'Go to an NJIT baseball match.',
            'Attend a volleyball match at NJIT.',
            'Watch a swimming competition at NJIT.',
            'Participate in an intramural sport at NJIT.',
            'Join a workout session at NJIT fitness center.',
            'Attend a fencing match at NJIT.',
            'Participate in a yoga class at NJIT.',
            'Watch a tennis match at NJIT.',
            'Attend an NJIT track and field event.',
            'Join a Zumba session at NJIT.',
            'Watch a women\'s lacrosse match at NJIT.',
            'Attend an esports event at NJIT.',
            'Join a climbing competition at NJIT.',
            'Watch a hockey game at NJIT.',
            'Join a spin class at NJIT.',
            'Watch a NJIT wrestling match.',
            'Attend a rugby game at NJIT.',
            'Join a weightlifting session at NJIT.',
            'Attend a martial arts class at NJIT.',
            'Join a badminton tournament at NJIT.'
        ],
        'faculty': [
            'Find a professor from the College of Science and Liberal Arts.',
            'Take a selfie with a professor from the College of Architecture and Design.',
            'Locate a professor from the Martin Tuchman School of Management.',
            'Have a chat with a professor from the College of Computing Sciences.',
            'Locate a faculty member from the Department of Biomedical Engineering.',
            'Meet a professor from the Department of Mechanical and Industrial Engineering.',
            'Find a professor from the Department of Chemical and Materials Engineering.',
            'Find a faculty member from the Department of Electrical and Computer Engineering.',
            'Meet a professor from the Department of Civil and Environmental Engineering.',
            'Attend a lecture by a professor from the Department of Physics.',
            'Locate a professor from the Department of Mathematical Sciences.',
            'Attend a workshop by a professor from the Department of Humanities.',
            'Meet a professor from the Department of History.',
            'Find a professor from the Department of Biological Sciences.',
            'Locate a professor from the Department of Chemistry and Environmental Science.',
            'Attend a seminar by a professor from the Department of Informatics.',
            'Meet a professor from the Department of Computer Science.',
            'Find a professor from the Department of Information Systems.',
            'Locate a professor from the Department of Management.',
            'Attend a lecture by a professor from the Department of Finance.',
            'Find a professor from the Department of Marketing.',
            'Locate a professor from the Department of Industrial Design.'
        ],
        'study': [
            'Find a study spot in the Van Houten Library.',
            'Locate a quiet place to study in the NJIT Campus Center.',
            'Take a picture of your favorite study spot on campus.',
            'Locate a study spot in the GITC building.',
            'Find a quiet place to study in the Martin Tuchman School of Management.',
            'Locate a study spot in the NJIT Wellness and Events Center.',
            'Find a quiet place to study in the Albert Dorman Honors College.',
            'Locate a study spot in the Central King Building.',
            'Find a quiet place to study in the Eberhardt Hall.',
            'Locate a study spot in the Faculty Memorial Hall.',
            'Find a quiet place to study in the NJIT Child Care Center.',
            'Locate a study spot in the NJIT Warren Street Village.',
            'Find a quiet place to study in the NJIT Microelectronics Center.',
            'Locate a study spot in the NJIT Life Sciences and Engineering Center.',
            'Find a quiet place to study in the NJIT Green building.',
            'Locate a study spot in the NJIT Fenster Hall.',
            'Find a quiet place to study in the NJIT Weston Hall.',
            'Locate a study spot in the NJIT Cypress Hall.',
            'Find a quiet place to study in the NJIT Summit Street Apartment.',
            'Locate a study spot in the NJIT Greek Village Lawn.',
            'Find a quiet place to study in the NJIT Student Mall.',
            'Locate a study spot in the NJIT Ying Wu College of Computing.'
        ],
        'food': [
            'Try a meal from the NJIT Campus Center food court.',
            'Grab a coffee from the NJIT Starbucks.',
            'Enjoy a snack from the NJIT convenience store.',
            'Try the sushi at the NJIT Campus Center.',
            'Enjoy a meal at the NJIT Gourmet Dining.',
            'Have a coffee at the NJIT Tech Cafe.',
            'Try a pizza at the NJIT Pizzaville.',
            'Enjoy a meal at the NJIT Highlander Pub.',
            'Try a burger at the NJIT Burger King.',
            'Have a meal at the NJIT Campus Grill.',
            'Try a sub at the NJIT Subconnection.',
            'Enjoy a snack at the NJIT Moe\'s Southwest Grill.',
            'Try a breakfast at the NJIT Dunkin Donuts.',
            'Enjoy a meal at the NJIT Ray\'s Cafe.',
            'Have a meal at the NJIT Village Market.',
            'Try a sandwich at the NJIT Jersey Mike\'s Subs.',
            'Enjoy a snack at the NJIT Elements.',
            'Try a smoothie at the NJIT Freshens.',
            'Have a meal at the NJIT Resident Dining Hall.',
            'Try a salad at the NJIT Saladworks.',
            'Enjoy a snack at the NJIT Tech Cafe Bakery.',
            'Have a meal at the NJIT Warren Street Cafe.'
        ]
    };

    var challengeDiv = document.getElementById('challenge-' + challengeType);
    var randomChallenge = challenges[challengeType][Math.floor(Math.random() * challenges[challengeType].length)];
    challengeDiv.textContent = randomChallenge;
}
